Class {
	#name : #CSE18NModel,
	#superclass : #MooseModel,
	#category : #'CasinoExtension-18N-Model-Model'
}

{ #category : #accessing }
CSE18NModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' 'Casino-Model-UI-SubEntities' 'Casino-Model-Layout' #'Casino-Model' #'Casino-18N-Model')
]

{ #category : #meta }
CSE18NModel class >> annotation [
	<FMClass: #CSE18NModel super: #MooseModel>
	<package: #'CasinoExtension-18N-Model'>
	<generated>
]
