Class {
	#name : #CS18NModel,
	#superclass : #MooseModel,
	#category : #'Casino-18N-Model-Model'
}

{ #category : #accessing }
CS18NModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query')
]

{ #category : #meta }
CS18NModel class >> annotation [
	<FMClass: #CS18NModel super: #MooseModel>
	<package: #'Casino-18N-Model'>
	<generated>
]

{ #category : #testing }
CS18NModel class >> canBeImportedFromFile [
	<generated>
	^true
]
